### PR TITLE
Prevent linter message from wrapping

### PR DESCRIPTION
**Pull request by simurai**
Fixes:

screenshot_from_2015-07-16_08-09-11_360

### CODE REVIEW

**Comment by steelbrain** [comment]
LGTM. To fellow reviews: It does has a downside that the tooltip's tip is no more exactly on the spot but I say it's worth it.

**Comment by simurai** [comment]
> It does has a downside that the tooltip's tip is no more exactly on the spot

Right. Actually even with wrapping, the tip can still be pushed away from the spot when there is little space.

**Comment by simurai** [comment]
Alternatively, the whole lines could wrap too with:

```css
linter-message {
  flex-wrap: wrap;
}
```

tooltip

**Comment by steelbrain** [comment]
Beautiful :heart:

**Comment by simurai** [comment]
Now the alignment could still be improved. The 2nd line isn't aligned like the badge and 3rd line. I'll do that tomorrow.

**Comment by simurai** [comment]
Ok, now each item wraps, but if there is even less space or the message is long, the text wraps too:

tooltip

I saw there is a `linter-multiline-message`. How does that show up? Haven't tested how that looks.

**Comment by joefitzgerald** [comment]
Please take a look at ac+, which flips the direction of the tool tip when you approach the right.

**Comment by park9140** [comment]
@simurai, as @joefitzgerald  suggests flipping the view would be better, additionally we should probably use the editor window boundry as the overflow so that we can use as much space as possible.

**Comment by simurai** [comment]
@park9140 This PR fixes just the wrapping. Doesn't have to be final solution, just improvement over the current (broken) state.

Flipping would definitely be a good to have. Anyone wants to tackle this in another PR?

**Comment by steelbrain** [comment]
@simurai should I merge this in?

**Comment by simurai** [comment]
@steelbrain Sure, if you like it. As said, it just improves the current wrapping that looks kinda broken.

**Comment by simurai** [comment]
btw. something I was thinking. Is it necessary for the inline message to show what line it is? Because if you click it, the only thing it does is go to the beginning, but it might not be that necessary.

**Comment by steelbrain** [comment]
where do we show it then if not on the current line?

**Comment by simurai** [comment]
It's still in the bottom panel, just not inline. Because inline, you already know what line and don't need a link.

screen shot 2015-07-23 at 10 27 10 am

**Comment by steelbrain** [comment]
The inline bubble is there for the traces, that help the person get to the definition of the error object by just clicking a link.
screenshot from 2015-07-22 19-32-10

I use it everday and it boosts my productivity.

**Comment by simurai** [comment]
> get to the definition of the error object by just clicking a link.

Ohh.. I see. Didn't know about that Trace thing. Ok, nevermind then.

**Comment by nelson6e65** [comment]
> So removing the line info makes the tooltip a bit shorter.

Oh... I was thinking about it too. #776

**Pull request merged**
