### PR TITLE
Fix for #859

### PR DESCRIPTION
**Pull request by JohnMurga**
A two line fix to #859

### CODE REVIEW

**Comment by steelbrain** [comment]
Screenshots of before and after would be appreciated

**Comment by JohnMurga** [comment]
untitled

**Comment by steelbrain** [comment]
Nice. A changelog entry would be appreciated, write it under `Upcoming` title

**Comment by JohnMurga** [comment]
Done ... Is that what you meant ?

**Comment by steelbrain** [comment]
LGTM Thanks

**Pull request merged**
