### PR TITLE
Auto updates

### LINKED ISSUE #960: Auto-Updates
I am thinking of an option, that's enabled by default, that checks for updates for linter package and installs them.

What do you think guys?
cc @k2b6s9j @SpainTrain @Arcanemagus @atom-community/linter-contributors

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #960

[Review on Reviewable](https://reviewable.io/reviews/atom-community/linter/991)

### CODE REVIEW

**Comment by kepler0** [comment]
The implementation looks great. I still don't know that I support the idea though...

**Comment by blakeembrey** [comment]
@steelbrain I just wanted to chime in too, but I would personally prefer not to do this in general. If people aren't updating, there's probably some reason. Also, if I look over the code correctly, this is only handling Atom startup? What about when the user has a long running editor open? I normally have mine open and running for weeks, but the updates come to me as usual still.

**Comment by steelbrain** [comment]
@blakeembrey People usually don't upgrade because they don't see the upgrade notification or don't pay attention to it. There are times when we introduce a bug accidentally and then immediately push a release that fixes that, this will make sure the users have the latest version of linter installed. and because we don't break the provider API, the latest version never hurts.

**Comment by steelbrain** [comment]
@blakeembrey I've updated the package to now query for updates each 12 hours

**Comment by kepler0** [comment]
There should be an informal study if this behavior would influence users who use Atom heavily.

Perhaps start with a survey on the Atom Slack.

**Comment by kepler0** [comment]
I'd also like to know the opinion of this from larger project which rely on Linter (OmniShard, Ionide, Nuclide, etc.)

**Comment by steelbrain** [comment]
After some discussion with @kepler0 I've decided not to do this in our package, we'll wait for core to do this instead

**Pull request closed without merging**
