### PR TITLE
Make linter panel resizable

### PR DESCRIPTION
**Pull request by steelbrain**
A long awaited feature :smiley: 
State persistence will be coming soon
Fixes https://github.com/atom-community/linter/issues/880

[Review on Reviewable](https://reviewable.io/reviews/atom-community/linter/910)

### CODE REVIEW

**Comment by k2b6s9j** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atom-community/linter/910)

**Comment by k2b6s9j** [comment]
Code's looking good. Haven't tried it out locally though.

**Comment by steelbrain** [comment]
@k2b6s9j and you should :wink:

**Comment by steelbrain** [comment]
@atom-community/linter-contributors any comments/suggestions?

**Comment by Arcanemagus** [comment]
Seems to work fine for me, only thing I can think of is the functionality isn't exposed at all (no resize cursor when mousing over the top of the linter panel), but that's a minor thing.

**Comment by steelbrain** [comment]
Merging this for now. Persistence and maybe a pointer icon would be added in future PRs.

**Pull request merged**
