### PR TITLE
Messages per buffer fix

### PR DESCRIPTION
**Pull request by asutherland**
I think this implements what we discussed in #871.  Note that the tests are currently a separate commit since it lets me (and you if you like) easily verify that the current implementation fails the test and that with the fix everything is happy.  I would squash them after addressing any concerns you have prior to requesting final landing.  (Or you can squash them or do whatever you like.)

Please do provide idiomatic guidance on the spec file if it's not to your liking.  I don't do a lot of BDD testing and I worry that I may have done too much prep logic.  (I could see adding more it() cases for the multiple pane case like covering editor deletion, which is why I factored it to be more reusable.)

### CODE REVIEW

**Comment by steelbrain** [comment]
This looks good to me. We never squash commits by the way. and You do have a little more "logic" in the prep part but it's fine to me as their purpose is to just test that stuff works.

A changelog entry would be nice before I merge it in

**Comment by asutherland** [comment]
I have pushed a changelog entry.  Also, glad to hear about the (lack of) squashing.

**Comment by steelbrain** [comment]
Ouch, I forgot to update the changelog about the recent release, would you mind merging master in?

**Comment by asutherland** [comment]
I did the non-history-rewriting thing.  Let me know if you do want some rewriting.

**Comment by steelbrain** [comment]
It's all fine, just waiting on CI

**Comment by steelbrain** [comment]
Thanks for your awesome contribution :clap:

**Comment by asutherland** [comment]
And thank you for the very pleasurable contribution experience!

**Pull request merged**
