### PR TITLE
Make single buffer work across multiple panes

### LINKED ISSUE #1007: Very unpredictable and buggy behaviour when file is open in multiple panes
Hi,

Sorry for an unspecific title and not much information. I want to give a brief description now, and _if this isn't an already known issue, I'll investigate, update title and post more information on this issue_.

I've used the linter for months now, and there is a bug annoying me all the time. If I have the same file open in multiple panes (which I do a lot. Split screen into the same file), it behaves very buggy and unpredictable. Often new errors are displayed only in one of the panes, but if I fix the error, I have to go back to the other pane and save the file from there before it gets linted again so the error disappears.

This happens with both `linter-eslint` and `linter-less`, so it is probably a problem with `linter` itself.

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #1007

ToDo
 - [x] Add spcs

[Review on Reviewable](https://reviewable.io/reviews/atom-community/linter/1018)

### CODE REVIEW

**Comment by steelbrain** [comment]
@Arcanemagus what's the status on your machine? It's still passing for me and failing on travis

**Comment by steelbrain** [comment]
The specs failing are not related to this PR in any way so merging in

**Comment by Arcanemagus** [comment]
Whoops, just now saw this. Status on my machine (after manual creation of `C:\tmp`):
image

**Comment by steelbrain** [comment]
Thanks for showing me that! I'll be improving the specs once I'm done with this major improvement of message-registry I'm working on

**Pull request merged**
