### PR TITLE
feat: use current file to detect syntax

### LINKED ISSUE #777: Markdown get linted
https://github.com/AtomLinter/linter-jshint/issues/136
https://github.com/AtomLinter/linter-jscs/issues/62

And I can reproduce it too with `linter-eslint`

Example code:

```markdown

# Some code example with syntax will be linted

```javascript
function () {}
```

The problem is that the whole file is getting linted so it throws a lot errors.

### PR DESCRIPTION
**Pull request by iam4x**
fixes #777

### CODE REVIEW

**Comment by steelbrain** [comment]
A test please.

**Comment by steelbrain** [comment]
@joefitzgerald I am not entirely sure if this would be correct as it doesn't report `source.php` for a php file. Any ideas, also how did you do it in AC+?

**Comment by iam4x** [comment]
@steelbrain Maybe we can have a special case for handling `.md` files? Instead of breaking actual way to find file syntax.

**Comment by steelbrain** [comment]
@iam4x but that would be monkey patching, I would prefer to fix this issue once and for all :)

**Comment by iam4x** [comment]
Let's wait for advices :)

**Comment by steelbrain** [comment]
Beautiful :)

**Comment by steelbrain** [comment]
No activity in a long long time

**Comment by steelbrain** [comment]
Also fixed in Atom by https://github.com/atom/language-gfm/pull/137

**Pull request closed without merging**
