### PR TITLE
Improve linter-panel style

### PR DESCRIPTION
**Pull request by UltCombo**
Only show scrollbar when there are scrollable contents.

### CODE REVIEW

**Comment by UltCombo** [comment]
It looks like Atom did not apply the custom scrollbars to this pane when I was testing. With one-dark-ui's scrollbars this change is not quite visible.

**Comment by steelbrain** [comment]
Changelog entry please.

**Comment by UltCombo** [comment]
Done.

**Comment by steelbrain** [comment]
Thanks.

**Comment by UltCombo** [comment]
No problem. :smile:

**Pull request merged**
