### PR TITLE
Show name of linter

### PR DESCRIPTION
**Pull request by steelbrain**
A long awaited and useful feature

[Review on Reviewable](https://reviewable.io/reviews/atom-community/linter/908)

### CODE REVIEW

**Comment by steelbrain** [comment]
screenshot
This is how it looks like at the moment. To add that label, providers just have to specify an optional attribute `name`. We could tweak it but I am not a designer so :wink: 
cc @simurai 

Also @basarat do you have any comments/suggestions? I remember you were using the html attribute to pass `TS` badge to messages

**Comment by basarat** [comment]
> I remember you were using the html attribute to pass TS badge to messages

That was just as a workaround. What you have looks awesome... will swap over. Thanks for the mention :rose:

**Comment by k2b6s9j** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atom-community/linter/908)

**Comment by k2b6s9j** [comment]
Looks purty. Well implemented. :shipit:

**Pull request merged**
